corona/corona/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from offers.views import AccountRegistrationView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/register', AccountRegistrationView.as_view(), name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('webpush/', include('webpush.urls')),
    path('metrics/' + settings.PROMETHEUS_PATH_SECRET + '/', include('django_prometheus.urls')),
    path('', include('offers.urls')),
]

corona/offers/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from offers.views import OfferSearchView, ProfileView, EditProfileView, \
    SendMessageView, MessageSentView, SafetyInformationView, AddressFromLocationAjaxView, AddressAutocompleteAjaxView, \
    OffersView, DeleteUserView, MessageErrorView, ActivateAccountView, ResendActivationMailView, MessagesView, \
    PushNotificationServiceWorkerView, ImprintView, PrivacyDeclarationView, ChangePasswordView, OverviewMapView, CssView

urlpatterns = [
    path('offers/', login_required(OffersView.as_view()), name='offers'),
    path('profile/', login_required(ProfileView.as_view()), name='profile'),
    path('profile/change_password/', login_required(ChangePasswordView.as_view()), name='change_password'),
    path('profile/<str:slug>/edit/', login_required(EditProfileView.as_view()), name='edit_profile'),
    path('profile/<int:pk>/delete/', login_required(DeleteUserView.as_view()), name='delete_user'),
    path('profile/<str:slug>/message/', SendMessageView.as_view(), name='send_message'),
    path('map/', OverviewMapView.as_view(), name='overview_map'),
    path('messages/', login_required(MessagesView.as_view()), name='messages'),
    path('message/sent/', MessageSentView.as_view(), name='message_sent'),
    path('message/error/', MessageErrorView.as_view(), name='message_error'),
    path('information/safety/', SafetyInformationView.as_view(), name='safety_information'),
    path('ajax/address/', AddressFromLocationAjaxView.as_view(), name='ajax_address'),
    path('ajax/autocomplete/', AddressAutocompleteAjaxView.as_view(), name='ajax_autocomplete'),
    path('activate/resend-mail/', login_required(ResendActivationMailView.as_view()), name='resend_activation_mail'),
    path('activate/<str:slug>/<str:token>/', ActivateAccountView.as_view(), name='activate_account'),
    path('imprint/', ImprintView.as_view(), name='imprint'),
    path('privacy/', PrivacyDeclarationView.as_view(), name='privacy'),
    path('sw.js', PushNotificationServiceWorkerView.as_view(), name='push_service_worker'),
    path('styles.css', CssView.as_view(), name='css_styles'),
    path('', OfferSearchView.as_view(), name='search'),
]

corona/offers/models.py
import hashlib
import random

from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.contrib.gis.db.models.functions import Distance
from django.core.mail import send_mail
from django.db.models import F
from django.urls import reverse_lazy, reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django_prometheus.models import ExportModelOperationsMixin
from webpush import send_user_notification

from offers.helper import location_from_address, create_activation_token, create_profile_slug
from offers.mail_templates import CONTACT_MAIL_FROM, CONTACT_MAIL_SUBJECT, ACTIVATION_MAIL_SUBJECT, \
    ACTIVATION_MAIL_FROM, ACTIVATION_MAIL_BODY

DAYTIME_CHOICES = (
    ('', _('-- Zeit filtern --')),
    ('MORNING', _('Morgens')),
    ('NOON', _('Mittags')),
    ('AFTERNOON', _('Nachmittags')),
    ('EVENING', _('Abends')),
)


class ProviderProfile(ExportModelOperationsMixin('profile'), models.Model):
    """
    A provider profile is in a one-to-one relationship with a user. It extends the user profile with some settings that
    are shared among the user's offers.

    The user sets the location with some radius where they want to offer help.

    Radius is in meters.
    """

    class Meta:
        verbose_name = _('Anbieterprofil')
        verbose_name_plural = _('Anbieterprofile')

    RADIUS_CHOICES = (
        (1000, '1 km'),
        (2000, '2 km'),
        (3000, '3 km'),
        (4000, '4 km'),
        (5000, '5 km'),
        (10000, '10 km'),
        (20000, '20 km'),
        (50000, '50 km'),
    )

    MOBILITY_CHOICES = (
        ('NA', _('keine Angabe')),
        ('FOOT', _('zu Fuß / ÖPNV')),
        ('BIKE', _('Fahrrad')),
        ('MOTOR_SCOOTER', _('Motorroller')),
        ('CAR', _('Auto')),
    )

    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)

    display_name = models.CharField(max_length=100, blank=True, verbose_name=_('Anzeigename (öffentlich)'))
    slug = models.CharField(max_length=20, default=create_profile_slug, unique=True, verbose_name=_('ID-Token'))
    activation_token = models.CharField(max_length=64, default=create_activation_token,
                                        verbose_name=_('Aktivierungsschlüssel'))
    activated = models.BooleanField(default=False, verbose_name=_('Aktiviert'))

    location = models.PointField(null=True, default=None)
    radius = models.IntegerField(choices=RADIUS_CHOICES, default=2000,
                                 verbose_name=_('Umkreis (nicht öffentlich)'))
    street = models.CharField(max_length=200, blank=True, verbose_name=_('Straße (nicht öffentlich)'))
    city = models.CharField(max_length=200, blank=True, verbose_name=_('Stadt (nicht öffentlich)'))

    mobility = models.TextField(choices=MOBILITY_CHOICES, default='NA',
                                verbose_name=_('Fortbewegungsmittel (öffentlich)'))
    offers_shopping = models.BooleanField(default=False, verbose_name=_('Einkaufen'))
    offers_petsitting = models.BooleanField(default=False, verbose_name=_('Gassi gehen'))
    offers_fetching_drugs= models.BooleanField(default=False, verbose_name=_('Medikamente abholen'))
    offers_sending_mail = models.BooleanField(default=False, verbose_name=_('Briefe einwerfen'))
    offers_courier = models.BooleanField(default=False, verbose_name=_('Kurierdienste'))
    comment = models.TextField(blank=True, verbose_name=_('Sonstige Hilfestellungen oder Kommentare (öffentlich)'))

    phone = models.CharField(max_length=50, blank=True,
                             verbose_name=_('Telefonnummer (öffentlich wenn du sie angibst)'))
    show_email = models.BooleanField(default=False, verbose_name=_('E-Mail-Adresse öffentlich anzeigen'))

    def __str__(self):
        return 'Profil für {}, {}, {}'.format(self.user.username, self.street, self.city)

    def save(self, *args, **kwargs):
        if self.street and self.city:
            self.location = location_from_address("{}, {}".format(self.street, self.city))
        super().save(*args, **kwargs)

    def send_activation_mail(self):
        activation_link = "{}{}".format(settings.HOST_NAME,
                                        reverse_lazy('activate_account', args=[self.slug, self.activation_token]))
        body = ACTIVATION_MAIL_BODY.format(name=self.user.username,
                                                             link=activation_link,
                                                             domain=settings.DOMAIN_TEXT)
        subject = ACTIVATION_MAIL_SUBJECT.format(domain=settings.DOMAIN_TEXT)
        from_email = ACTIVATION_MAIL_FROM.format(domain=settings.DOMAIN_TEXT)

        send_mail(subject, body, from_email, [self.user.email], fail_silently=False)

    def get_blurred_location(self):
        # deterministic blurring is important to prevent information disclosure by averaging many requests
        random.seed(hashlib.sha256(self.slug.encode('UTF-8')).hexdigest())
        return {
            'x': self.location.x + random.random()*settings.BLUR_RADIUS - settings.BLUR_RADIUS/2,
            'y': self.location.y + random.random()*settings.BLUR_RADIUS - settings.BLUR_RADIUS/2
        }


class Offer(ExportModelOperationsMixin('offer'), models.Model):
    """
    An offer object is an offer by a logged-in user, offering some help.

    It can be found by anybody using the frontend search.
    It can be managed by its logged-in owner user in the backend.
    """

    class Meta:
        verbose_name = _('Hilfsangebot')
        verbose_name_plural = _('Hilfsangebote')

    user = models.ForeignKey(User, related_name='offers', on_delete=models.CASCADE)

    date = models.DateField(default=now, verbose_name=_('Datum'))

    morning = models.BooleanField(default=False, verbose_name=_('Morgens'))
    noon = models.BooleanField(default=False, verbose_name=_('Mittags'))
    afternoon = models.BooleanField(default=False, verbose_name=_('Nachmittags'))
    evening = models.BooleanField(default=False, verbose_name=_('Abends'))

    def __str__(self):
        return '{} am {}'.format(self.user.get_full_name(), self.date)

    @staticmethod
    def offers_in_range(query_location):
        return Offer.objects.annotate(distance=Distance('user__profile__location', query_location)) \
            .filter(user__profile__activated=True) \
            .filter(distance__lte=F('user__profile__radius')).order_by('-distance')

    @staticmethod
    def offers_in_range_and_date(query_location, date):
        return Offer.offers_in_range(query_location).filter(date=date)


class Message(ExportModelOperationsMixin('message'), models.Model):
    """
    A message is an (e-mail) message that an anonymous user sent to a logged-in user who put in an offer.

    It is sent by mail to the logged-in user.
    It is stored in database for future troubleshooting.
    """

    class Meta:
        verbose_name = _('Gesendete Nachricht')
        verbose_name_plural = _('Gesendete Nachrichten')

    recipient = models.ForeignKey(User, related_name='received_messages', on_delete=models.CASCADE)

    sender_name = models.CharField(max_length=100, blank=True)
    sender_email = models.CharField(max_length=100, blank=True)
    sender_phone = models.CharField(max_length=100, blank=True)

    message = models.TextField(blank=True)

    date = models.DateTimeField(default=now)

    def __str__(self):
        return "Nachricht am {} von {} an {}".format(self.date, self.sender_name, self.recipient.get_full_name())

    def send(self):
        subject = CONTACT_MAIL_SUBJECT.format(domain=settings.DOMAIN_TEXT)
        from_email = CONTACT_MAIL_FROM.format(domain=settings.DOMAIN_TEXT)

        send_mail(subject, self.message, from_email, [self.recipient.email], fail_silently=False)

        payload = {
            'head': CONTACT_MAIL_SUBJECT.__str__(),
            'body': self.message,
            'url': settings.HOST_NAME + reverse('messages')
        }

        send_user_notification(user=self.recipient, payload=payload, ttl=1000)


class Website(models.Model):
    """
    A website is a small-CMS-style website content.

    It is used by template pages and referenced by a name.
    We use it to provide different content on e.g. the homepage for different deployments of the app.
    """

    class Meta:
        verbose_name = _('Webseiten-Inhalt')
        verbose_name_plural = _('Webseiten-Inhalte')
        unique_together = ['name', 'language']

    SITE_NAMES = (
        ('HOME', _('Startseite')),
        ('SAFETY', _('Sicherheits-Informationen')),
        ('IMPRINT', _('Impressum')),
        ('PRIVACY', _('Datenschutz')),
    )

    name = models.CharField(choices=SITE_NAMES, max_length=100)
    language = models.CharField(choices=settings.LANGUAGES, max_length=100)
    content = models.TextField(blank=True)

    def __str__(self):
        return "{} auf {}".format(self.get_name_display(), self.get_language_display())

corona/offers/forms.py
from captcha.fields import ReCaptchaField
from django import forms
from django.contrib.auth.models import User
from django.forms import modelformset_factory
from django.utils.translation import gettext_lazy as _

from offers.models import Offer, ProviderProfile, DAYTIME_CHOICES


class OfferSearchForm(forms.Form):
    where = forms.CharField(label='where', max_length=100,
                            widget=forms.TextInput(attrs={'placeholder': _('Wo? (Straße und Ort)'), 'autocomplete':'off'}))
    when = forms.DateTimeField(label='when', input_formats=['%d.%m.%Y'],
                               widget=forms.TextInput(attrs={'placeholder': _('Wann?'), 'autocomplete': 'off'}))

    mobility = forms.ChoiceField(choices=[('', _('-- Mobilität filtern --'))]+list(ProviderProfile.MOBILITY_CHOICES),
                                 required=False, initial='')
    daytime = forms.ChoiceField(choices=DAYTIME_CHOICES, required=False, initial='')


class SendMessageForm(forms.ModelForm):
    sender = forms.CharField(label=_('Dein Name'), max_length=100, required=False)
    email = forms.EmailField(label=_('Deine E-Mail-Adresse'), max_length=100, required=False)
    phone = forms.CharField(label=_('Deine Telefonnummer (optional)'), max_length=100, required=False)
    message = forms.CharField(label=_('Nachricht'), max_length=1000, widget=forms.Textarea())
    captcha = ReCaptchaField()

    class Meta:
        model = User
        fields = ['sender', 'email', 'phone', 'message']


class ProviderProfileForm(forms.ModelForm):
    display_name = forms.CharField(label=_('Anzeigename (öffentlich)'), max_length=100, required=True)
    email = forms.EmailField(label=_('E-Mail-Adresse'), disabled=True, required=False)
    street = forms.CharField(label=_('Straße (nicht öffentlich)'), max_length=200)
    city = forms.CharField(label=_('Stadt (nicht öffentlich)'), max_length=200)

    class Meta:
        model = ProviderProfile
        fields = ['display_name', 'street', 'city', 'radius', 'mobility',
                  'offers_shopping', 'offers_petsitting', 'offers_fetching_drugs', 'offers_sending_mail',
                  'offers_courier', 'phone', 'email', 'show_email', 'comment']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email')


class OfferForm(forms.ModelForm):
    date = forms.DateField(widget=forms.HiddenInput())

    class Meta:
        model = Offer
        fields = ['date', 'morning', 'noon', 'afternoon', 'evening']


class BaseOfferFormSet(forms.BaseModelFormSet):
    def __iter__(self):
        return iter(sorted(self.forms, key=lambda x: x['date'].value()))

    def __getitem__(self, index):
        return list(self)[index]


OfferFormSet = modelformset_factory(Offer, form=OfferForm, formset=BaseOfferFormSet, min_num=14, max_num=14)

corona/offers/templates/offers/base.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% trans "Wir stehen zusammen - Finde Hilfe in der Corona Krise" %}</title>

    <!-- Social Graph -->
    <meta property="og:image" content="{{ hostname }}{% static 'offers/images/screenshot.png' %}">
    <meta property="twitter:image" content="{{ hostname }}{% static 'offers/images/screenshot.png' %}">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'offers/custom-bootstrap.css' %}" />
    {% bootstrap_javascript jquery='full' %}

    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet" href="{% static 'offers/jquery.datetimepicker.min.css' %}" />
    <script src="{% static 'offers/jquery.datetimepicker.full.min.js' %}"></script>

    <!-- Leaflet -->
    <link rel="stylesheet" href="{% static 'offers/leaflet.css' %}" />
    <link rel="stylesheet" href="{% static 'offers/MarkerCluster.css' %}" />
    <link rel="stylesheet" href="{% static 'offers/MarkerCluster.Default.css' %}" />
    <script src="{% static 'offers/leaflet.js' %}"></script>
    <script src="{% static 'offers/leaflet.markercluster.js' %}"></script>

    <!-- jQuery UI -->
    <link rel="stylesheet" href="{% static 'offers/jquery-ui.min.css' %}" />
    <script src="{% static 'offers/jquery-ui.min.js' %}"></script>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'offers/fontawesome/css/all.min.css' %}" />

    <!-- Custom styles -->
    <link rel="stylesheet" href="{% url 'css_styles' %}" />

    <!-- Webpush -->
    <meta name="vapid-key" content="{{ vapid_key }}">

    <!-- Matomo -->
    <script type="text/javascript">
        var _paq = window._paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(["setCookieDomain", "*.www.{{ domain_text }}"]);
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
            var u="//www.{{ domain_text }}/matomo/";
            _paq.push(['setTrackerUrl', u+'matomo.php']);
            _paq.push(['setSiteId', '1']);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
        })();
    </script>
</head>
<body class="{% block bodyclass %}{% endblock %}">

<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'search' %}">
            <img src="{{ logo_url }}" height="100"
                 class="d-inline-block align-top" alt="{% trans 'Wir stehen zusammen' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="nav navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">{% trans "Abmelden" %}</a></li>
                    <li class="nav-item"><a href="{% url 'search' %}" class="nav-link">{% trans "Suche" %}</a></li>
                    <li class="nav-item"><a href="{% url 'overview_map' %}" class="nav-link">{% trans "Angebote" %}</a></li>
                    <li class="nav-item"><a href="{% url 'messages' %}" class="nav-link">{% trans "Nachrichten" %}</a></li>
                    <li class="nav-item"><a href="{% url 'profile' %}" class="nav-link">{% trans "Dein Profil" %}</a></li>
                    <li class="nav-item"><a href="{% url 'offers' %}" class="btn btn-primary">{% trans "Deine Zeiten" %}</a></li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'overview_map' %}" class="nav-link">{% trans "Angebote" %}</a></li>
                    <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">{% trans "Anmelden" %}</a></li>
                    <li class="nav-item"><a href="{% url 'register' %}" class="btn btn-primary">{% trans "Biete deine Hilfe an" %}</a></li>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="message {% if message.tags %}{{ message.tags }}{% endif %}">
                <div class="container">
                    {{ message }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}

{% block content %}
{% endblock %}

{% block footerpadding %}
<div class="padding-top-1"></div>
{% endblock %}

<footer>
    <div class="container">
        &copy; 2020 mach2media &middot;
        <a class="text-link" href="{% url 'imprint' %}">{% trans "Impressum" %}</a> &middot;
        <a class="text-link" href="{% url 'privacy' %}">{% trans "Datenschutz" %}</a> &middot;
        <a class="text-link" href="{% url 'safety_information' %}">{% trans "Sicherheits-Informationen" %}</a> &middot;

        <div class="language-switcher">
            <form action="{% url 'set_language' %}" method="post" class="form-inline" name="language-form">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}">
                <label for="id_language">{% trans 'Switch language:' %}</label>&nbsp;
                <select name="language" id="id_language" class="form-control input-sm w-initial">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                    {% endfor %}
                </select>
                <input type="submit" value="{% trans 'Sprache ändern' %}" class="btn btn-primary btn-sm">
            </form>
        </div>
    </div>
    <div class="padding-top-1"></div>
</footer>

<script>
    var languageForm = $("form[name='language-form']");
    $(":submit", languageForm).hide();
    $("select", languageForm).change(function(){languageForm.submit()});
</script>
</body>
</html>

corona/offers/templates/offers/home.html
{% extends 'offers/base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load i18n %}
{% load template_tags %}

{% block footerpadding %}{% endblock %}

{% block content %}
    <div class="bg-image">
        <div class="container padding-top-1">
            <div class="search-form">
                <div class="inner-search">
                    <h2>{% trans "Wir stehen zusammen. Finde Hilfe in der Corona-Krise" %}</h2>

                    <form method="POST" action="">
                        {% csrf_token %}

                        {{ form.where }}
                        <a href="#" id="locate">
                            <img src="{% static 'offers/images/crosshair.png' %}"
                                 alt="{% trans "Versuche mich zu orten" %}"
                                 title="{% trans "Versuche mich zu orten" %}" />
                        </a>

                        <div class="hidden-sm-up padding-top-1"></div>

                        {{ form.when }}
                        <a href="#" id="today">
                            <img src="{% static 'offers/images/today-icon.png' %}" alt="{% trans "Heute" %}"
                                 title="{% trans "Heute" %}" />
                        </a>

                        <div class="display-none">
                            {{ form.mobility }}
                            {{ form.daytime }}
                        </div>

                        <div class="hidden-sm-up padding-top-1"></div>
                        <input type="submit" value="{% trans "Suchen!" %}" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% cms_page 'HOME' %}

    <script>
        $(function () {
            let whereField = $('#id_where');
            let whenField = $('#id_when');

            // datepicker for when field
            whenField.datetimepicker({
                format: 'd.m.Y',
                timepicker: false
            });

            // image slideshow
            var images = ['{{ slideshow_first_image }}', '{% static 'offers/images/bild-2.jpg' %}',
                '{% static 'offers/images/bild-3.jpg' %}','{% static 'offers/images/bild-4.jpg' %}'];
            var index = 0;
            var period = 10000;

            var cycle = function() {
                index = (index + 1) % images.length;
                $('.bg-image').css({'background-image': 'url("'+images[index]+'")'});
                setTimeout(cycle, period);
            };

            setTimeout(cycle, period);

            // prefetch images
            var curImg = new Image();
            var prefetchNext = function(i) {
                curImg.src = images[i];
                curImg.onload = function() {
                    if (i < images.length - 1) {
                        prefetchNext(i+1);
                    }
                }
            };
            prefetchNext(1);

            // set date to today button
            $('#today').click(function () {
                var date = new Date();
                whenField.val((""+date.getDate()).padStart(2, "0") + "." + (""+(date.getMonth()+1)).padStart(2, "0") +
                    "." + date.getFullYear());
                return false;
            });

            // geolocation for where field
            $('#locate').click(function() {
                if (navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(function success (position) {
                        updateWhereFieldWithAddress(position.coords.latitude, position.coords.longitude);
                    }, function error (error) {
                        switch(error.code) {
                            case error.PERMISSION_DENIED:
                                // do nothing
                                break;
                            case error.POSITION_UNAVAILABLE:
                                alert("{% trans "Standortdaten sind nicht verfügbar." %}");
                                break;
                            case error.TIMEOUT:
                                alert("{% trans "Die Standortabfrage dauerte zu lange (Time-out)." %}");
                                break;
                            case error.UNKNOWN_ERROR:
                                alert("{% trans "Unbekannter Fehler." %}");
                                break;
                        }

                    });
                } else {
                    alert("{% trans "Ihr Browser unterstützt keine Ortung." %}");
                }
            });

            var updateWhereFieldWithAddress = function(lat, lng) {
                $.get('{% url 'ajax_address' %}', {
                    lat: lat,
                    lng: lng
                }, function (address) {
                    $('#id_where').val(address);
                });
            };

            // address autocomplete
            var getAutocompleteOptions = function(query, callback) {
                $.get('{% url 'ajax_autocomplete' %}', {
                    q: query
                }, function (response) {
                    suggestions = JSON.parse(response);
                    suggestions = suggestions.slice(0, Math.min(5, suggestions.length));
                    callback(suggestions);
                });
            };
            whereField.autocomplete({
                source: function(request, response) {
                    getAutocompleteOptions(request.term, response)
                },
                minLength: 3
            });

            // address local storage
            let LOCAL_STORAGE_LAST_QUERY = 'lastLocationQuery';
            let LOCAL_STORAGE_LAST_DATE = 'lastDateQuery';

            whereField.change(function() {
                localStorage.setItem(LOCAL_STORAGE_LAST_QUERY, $(this).val());
            });
            if(localStorage.getItem(LOCAL_STORAGE_LAST_QUERY)) {
                whereField.val(localStorage.getItem(LOCAL_STORAGE_LAST_QUERY));

            }
            whenField.change(function() {
                localStorage.setItem(LOCAL_STORAGE_LAST_DATE, $(this).val());
            });
            if (localStorage.getItem(LOCAL_STORAGE_LAST_DATE)) {
                whenField.val(localStorage.getItem(LOCAL_STORAGE_LAST_DATE));
            }
        });
    </script>
{% endblock %}

corona/offers/templates/offers/offer_list.html
{% extends 'offers/base.html' %}

{% block content %}
    <h2>Mein Anbieterprofil</h2>

    <p><b>Name:</b> {{ user.get_full_name }}</p>
    <p><b>Ort:</b> {{ user.profile.address }}, {{ user.profile.city }}</p>
    <p><b>Umkreis:</b> {{ user.profile.get_radius_display }}</p>
    <p><b>Fortbewegungsmittel:</b> {{ user.profile.get_mobility_display }}</p>
    <p><b>Kommentar:</b> {{ user.profile.comment }}</p>

    <div id="map" style="height: 400px; width: 600px;"></div>

    <a href="{% url 'edit_profile' user.profile.id %}">(Bearbeiten)</a>

    <hr />

    <h2>Angebotene Zeiten</h2>

    {% if object_list %}
        <ul>
            {% for offer in object_list %}
                <li>
                    {{ offer.start_time }} bis {{ offer.end_time.time }}
                    <a href="{% url 'delete_offer' offer.id %}">(Löschen)</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Du hast bisher keine Angebote erstellt.</p>
    {% endif %}

    <a href="{% url 'create_offer' %}">Füge eine Zeit hinzu!</a>

    <script type="text/javascript">
        $(function() {
            var lat = "{{ user.profile.location.x|stringformat:"f" }}";
            var lon = "{{ user.profile.location.y|stringformat:"f" }}";

            var map = L.map('map').setView([lat, lon], 14);

            L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
                attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                maxZoom: 18,
                id: 'mapbox/streets-v11',
                tileSize: 512,
                zoomOffset: -1,
                accessToken: '{{ mapbox_api_token }}'
            }).addTo(map);

            L.marker([lat, lon]).addTo(map);

            var circle = L.circle([lat, lon], {
                color: 'blue',
                fillColor: '#30f',
                fillOpacity: 0.5,
                radius: {{ user.profile.radius }}
            }).addTo(map);
        });
    </script>
{% endblock %}